project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "Statistikas"
  description: "Statistinės analizės ir konsultacijos"
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: https://github.com/Alaburda/statistikas
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/Alaburda/statistikas
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
